# ______   _______  _______ _________            _        _______ _________ _______  # 
#(  __  \ (  ____ \(  ___  )\__   __/|\     /|  ( (    /|(  ___  )\__   __/(  ____ \ #
#| (  \  )| (    \/| (   ) |   ) (   | )   ( |  |  \  ( || (   ) |   ) (   | (    \/ #
#| |   ) || (__    | (___) |   | |   | (___) |  |   \ | || |   | |   | |   | (__     #
#| |   | ||  __)   |  ___  |   | |   |  ___  |  | (\ \) || |   | |   | |   |  __)    #
#| |   ) || (      | (   ) |   | |   | (   ) |  | | \   || |   | |   | |   | (       #
#| (__/  )| (____/\| )   ( |   | |   | )   ( |  | )  \  || (___) |   | |   | (____/\ #
#(______/ (_______/|/     \|   )_(   |/     \|  |/    )_)(_______)   )_(   (_______/ #
#                                                                                    #

# The maximum number of players a Death Note can kill in its lifetime
# After this number is reached, a Death Note will simply stop working
# Set to -1 for no limit
max-uses: 10